### ISSUE TITLE
Сбор информации о пользователе

### ISSUE THREAD

**Issue by Avgany-23** [Avgany-23/VKinderBOT#2]
Использовать API VK. 

Даётся id пользователя в ВК, на основе этого id необходимо собрать информацию со страницы пользователя:
- ФИО
- пол (мужской/женский)
- возраст
- город проживания
- указанные интересы на странице
- фотографии со страницы (3-5 фотографий). Так же должно быть количество лайков к каждой фотографии

На выходе должен получиться словарь, включающий в себе id пользователя + всю информацию, которая написана выше

@Anastas0812

**Comment by Anastas0812** [comment]
сделано
